# Define the name of the GitHub Action workflow
name: ECS Cluster Deploy Drupal

# This workflow is manually triggered using the GitHub Actions UI
on:
  workflow_dispatch:
    # Define inputs that are required for the manual trigger
    inputs:
      Cluster_Name:
        description: 'Name of the ECS Cluster'  # Name of the EC2 instance
        required: true  # This input is required
      Region:
        description: 'AWS Region for the instance'  # AWS region where the instance will be created
        required: true  # This input is required
      # instanceType:
      #   description: 'AWS instance type'  # Type of the EC2 instance (e.g., t2.micro)
      #   required: true  # This input is required
      action:
        description: 'Action to perform (apply/destroy)'  # Action to be performed (create or delete the instance)
        required: true  # This input is required
      port_context:
        description: "port_context"
        required: true
      drupal_app_name:
        required: true
      database_name:
        required: true
      database_user_name:
        required: true
      database_password:
        required: true

# Jobs to be executed in this workflow
jobs:
  # Job for applying the EC2 instance
  apply-ecs-cluster:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Execute this job only if the action input is "apply"
    if: ${{ github.event.inputs.action == 'apply' }}

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a log message (apply)
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: "Initiating creation of ECS cluster: ${{ github.event.inputs.Cluster_Name }}."

            # Configure AWS credentials. Please store the value of these keys in GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.Region }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: .  # Assuming your Terraform files are in the root directory

      # Format Terraform code
      - name: Terraform Format
        run: terraform fmt
        working-directory: .

      # Validate the Terraform code
      - name: Terraform Validate
        run: terraform validate
        working-directory: .

      #################################################
      - name: Run Terraform Plan
        env:
          TF_VAR_cluster_name=${{ github.event.inputs.Cluster_Name }}
          TF_VAR_Region=${{ github.event.inputs.Region }}
          TF_VAR_app_name= ${{github.event.inputs.drupal_app_name }}
          TF_VAR_DRUPAL_DB_NAME= ${{github.event.inputs.database_name}}
          TF_VAR_DRUPAL_DB_USER= ${{github.event.inputs.database_user_name}}
          TF_VAR_DRUPAL_DB_PASSWORD= ${{github.event.inputs.database_password}}
        run: |
          terraform plan -var -out=tfplan
          terraform show -json tfplan > tfplan.json
        working-directory: .

      - name: Extract Resource Information
        id: extract
        run: |
          # Use jq to extract relevant information from the JSON plan
          resource_info=$(jq -r '.resource_changes[] | select(.change.actions[] == "create") | .address' tfplan.json)

          # Check if the variable is empty and handle accordingly
          if [ -z "$resource_info" ]; then
            echo "RESOURCE_INFO=none" >> $GITHUB_ENV
          else
            # Ensure proper formatting: replace newlines with commas, then escape commas for GitHub Actions
            formatted_resource_info=$(echo "$resource_info" | tr '\n' ',')
            formatted_resource_info=${formatted_resource_info%,}  # Remove trailing comma
            
            # Replace commas with a special escape sequence to avoid issues with GitHub Actions
            echo "RESOURCE_INFO=${formatted_resource_info//,\\n}" >> $GITHUB_ENV
          fi


      - name: Inform Port about the status of the ECS cluster creation
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          status: "SUCCESS"
          runId:  ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            ECS cluster creation has been completed.
            Cluster Name: ${{ github.event.inputs.Cluster_Name }}
            Created resources: ${{ env.RESOURCE_INFO }}
      ###################################################

      # Apply the Terraform plan to create the EC2 instance
      - name: Terraform Apply
        env:
          TF_VAR_cluster_name=${{ github.event.inputs.Cluster_Name }}
          TF_VAR_Region=${{ github.event.inputs.Region }}
          TF_VAR_app_name= ${{github.event.inputs.drupal_app_name }}
          TF_VAR_DRUPAL_DB_NAME= ${{github.event.inputs.database_name}}
          TF_VAR_DRUPAL_DB_USER= ${{github.event.inputs.database_user_name}}
          TF_VAR_DRUPAL_DB_PASSWORD= ${{github.event.inputs.database_password}}
        run: |
          terraform apply -auto-approve
        working-directory: .
    #########################################
    ## Log for the getport
    ##########################################
      # - name: Inform Port about the status of the ECS cluster creation
      #   if: ${{ github.event.inputs.action == 'apply' }}
      #   uses: port-labs/port-github-action@v1
      #   with:
      #     clientId: ${{ secrets.PORT_CLIENT_ID }}
      #     clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
      #     baseUrl: https://api.getport.io
      #     operation: PATCH_RUN
      #     status: "SUCCESS"
      #     runId: ${{ env.PORT_RUN_ID }}
      #     logMessage: "ECS cluster creation has been completed: ${{ github.event.inputs.Cluster_Name }}"




  # Job for destroying the EC2 instance
  destroy-ecs-cluster:
    runs-on: ubuntu-latest
    
    # Execute this job only if the action input is "destroy"
    if: ${{ github.event.inputs.action == 'destroy' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Configure AWS credentials. Please store the value of these keys in GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.Region }}
        
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: .
      
      # Format Terraform code
      - name: Terraform Format
        run: terraform fmt
        working-directory: .

      - name: Run Terraform Plan
        run: |
          terraform plan -var cluster_name=${{ github.event.inputs.Cluster_Name }} \
          -var Region=${{ github.event.inputs.Region }} \
          -var app_name= ${{github.event.inputs.drupal_app_name }} \
          -var DRUPAL_DB_NAME= ${{github.event.inputs.database_name}} \
          -var DRUPAL_DB_USER= ${{github.event.inputs.database_user_name}} \
          -var DRUPAL_DB_PASSWORD= ${{github.event.inputs.database_password}} \
          -out=tfplan
        # terraform show -json tfplan > tfplan.json
        working-directory: .

      - name: Extract Resource Information
        id: extract
        run: |
          created_resources=$(jq -r '.resource_changes[] | select(.change.actions[] == "create") | .address' tfplan.json)
          destroyed_resources=$(jq -r '.resource_changes[] | select(.change.actions[] == "destroy") | .address' tfplan.json)

          # Check if the variables are empty and handle accordingly
          if [ -z "$destroyed_resources" ]; then
            echo "DESTROYED_RESOURCES=none" >> $GITHUB_ENV
          else
            # Replace newlines with commas for a better environment variable format
            destroyed_resources=$(echo "$destroyed_resources" | tr '\n' ',')
            # Remove trailing comma
            destroyed_resources=${destroyed_resources%,}
            echo "DESTROYED_RESOURCES=${destroyed_resources}" >> $GITHUB_ENV
          fi

      # Destroy the resources managed by Terraform
      - name: Terraform Destroy
        run: |
          terraform destroy -var cluster_name=${{ github.event.inputs.Cluster_Name }} \
          -var Region=${{ github.event.inputs.Region }} \
          -var app_name= ${{github.event.inputs.drupal_app_name }} \
          -var DRUPAL_DB_NAME= ${{github.event.inputs.database_name}} \
          -var DRUPAL_DB_USER= ${{github.event.inputs.database_user_name}} \
          -var DRUPAL_DB_PASSWORD= ${{github.event.inputs.database_password}} \
          -auto-approve
        working-directory: .

      - name: Inform Port about the status of the ECS cluster destruction
        if: ${{ github.event.inputs.action == 'destroy' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          status: "SUCCESS"
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: "ECS cluster destruction has been completed: ${{ github.event.inputs.Cluster_Name }}"

      - name: Inform Port about the status of the ECS cluster destruction
        if: ${{ github.event.inputs.action == 'destroy' }}
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          status: "SUCCESS"
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            ECS cluster destruction has been completed.
            Destroyed resources: ${{ env.DESTROYED_RESOURCES }}
            Cluster Name: ${{ github.event.inputs.Cluster_Name }}
